### ISSUE TITLE
Is there any way to use your docker image on arm for a Raspberry Pi 3 ?

### ISSUE THREAD

**Issue by chicungunya** [sleeyax/pimpmystremio-docker#1]
Hello @sleeyax ,
Thank you for your docker image.
Is that possible to update if for a Rasperrby Pi 3 (arm)
Thanks a lot!

**Comment by sleeyax** [comment]
Did you try to run it on rpi yet? What output do you get?

**Comment by chicungunya** [comment]
Yes it works, I used your tuto https://gist.github.com/sleeyax/e9635eb352a4fcdf94194f763d743689 
But I prefer a docker image to start and stop it when I want. But when I use yours, I have an error because it's amd64 and not arm.
I am new in Docker that's why I ask you some help.

Thanks !

**Comment by sleeyax** [comment]
> But when I use yours, I have an error because it's amd64 and not arm.

That's because PMS only supports a x64 linux binary.

I'll try to create a docker image from source code and see if that works...

**Comment by sleeyax** [comment]
Well I tried to build an image targeting `arm/v7` but now I get `standard_init_linux.go:219: exec user process caused: exec format error`. Not sure what's causing this 🤷‍♂️

**Comment by sleeyax** [comment]
I'm thinking it has something to do with the released PMS binaries. They're only targetting win, linux & macos based on the hosts nodejs version & arch which is x64 in this case.

Looking at the packager PMS uses ([pkg](https://www.npmjs.com/package/pkg)), there's other packaging options to try. However, there seems to be [several issues](https://github.com/vercel/pkg/issues/333) when trying to build targeting ARMv7 from windows to linux.

The alternative is to build PMS from source inside the docker container (similar to what you're doing when you follow that guide I wrote). The downside to this is that the final docker image size will be larger.

**Comment by chicungunya** [comment]
Hello @sleeyax 
Thanks a lot for your test ! Hope someone will find the solution !

**Comment by sleeyax** [comment]
Ok so it is possible to build a binary for rpi using a [pre-packaged node binary](https://github.com/yao-pkg/pkg-binaries) and pkg. However, the packaging process doesn't work that well and it spits a lot of errors making PMS runnable - but unusable since none of the addons work properly.

```
Add-on installed: TheBeastLT/stremio-cdn-videos
Error: Cannot find module './shims/youtube-dl'
Require stack:
- /snapshot/src/lib/vm.js
- /snapshot/src/lib/addon.js
- /snapshot/src/lib/children.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /snapshot/src/lib/vm.js:67:24
    at Array.forEach (<anonymous>)
    at Object.run (/snapshot/src/lib/vm.js:56:17)
    at /snapshot/src/lib/addon.js:238:29
(node:2516) UnhandledPromiseRejectionWarning: Error: Cannot find module './shims/youtube-dl'
Require stack:
- /snapshot/src/lib/vm.js
- /snapshot/src/lib/addon.js
- /snapshot/src/lib/children.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /snapshot/src/lib/vm.js:67:24
    at Array.forEach (<anonymous>)
    at Object.run (/snapshot/src/lib/vm.js:56:17)
    at /snapshot/src/lib/addon.js:238:29
(node:2516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: stremio-cdn-videos - add-on timed out while trying to start
    at timeoutCb (/snapshot/src/lib/addon.js:219:14)
    at /snapshot/src/node_modules/lodash/lodash.js:10076:25
```

**Comment by sleeyax** [comment]
Youtube-dl was taken down recently, so maybe that's why it fails to package it on that part. If that's the case, PMS requires an update and I can't really do much about it bcs I can't build the binary properly...

**Comment by sleeyax** [comment]
And building from source seems to work but then `forked-systray` fails to install because it the postinstall script doesn't go well with docker.

I might look into this later, I don't have time to figure this out now.

**Comment by sleeyax** [comment]
For now your best bet is to run PMS directly on your rpi (install from source, partially following the guide). You can keep it running in the background using [screen](https://linuxize.com/post/how-to-use-linux-screen/) and to shut it down go to PMS interface settings > shutdown. 

Tip: install the [JuiceSSH](https://juicessh.com/) app on your phone to connect to your pi on the go :P

**Comment by sleeyax** [comment]
Ok I got something working from source code by removing `forked-systray` before installation of the node dependencies. I think this does the job for now, untill PMS adds offical rpi binaries. 

Run the new image from your pi like this: `docker run -p 7777:7777 sleeyax/pimpmystremio:fromsource`.

**Comment by chicungunya** [comment]
@sleeyax You're a genius.
MERCI !
